name: Soheil Eshghi
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Soheil Eshghi
tagline:          Soheil Eshghi - Postdoctoral Associate - Yale Institute for Network Science
url:              http://www.soheileshghi.com
shorturl:         soheileshghi.com

paginate: 5
paginate_path: "/blog/page:num/"


scholar:
  style: _publications/ieee.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_publications
  bibliography: references.bib
  bibliography_template: <abbr>[{{key}}] </abbr>{{reference}}{% if entry.author %}
  <ul class="nav nav-pills">
    <li><a data-toggle="collapse" href="#{{key}}-author">
    </a></li>
  </ul>
  {% endif %} #""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    publications
  details_layout: details.html
  details_link:   Details

  query: "@*"


# Gems
gems: [jekyll-paginate,rake,reduce]
