name: Soheil Eshghi
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Soheil Eshghi
tagline:          Soheil Eshghi
url:              http://www.soheileshghi.com
shorturl:         soheileshghi.com

paginate: 5
paginate_path: "/blog/page:num/"

navigation:
  - title: publications
    url: /publications/
  - title: research
    url: /research/
  - title: teaching
    url: /teaching/
  - title: professional
    url: /professional/
  - title: blog
    url: /blog/




scholar:
  style: apa-6th-edition
  locale: en

  #bibtex_filters:
  #- superscript
  #- latex

  sort_by: year,month,author
  order: descending,descending,ascending

  source: ./_publications
  bibliography: references.bib
  bibliography_template: bibtemplate

  repository: ./repository

  replace_strings: true
  join_strings:    true

  query: "@*"

#scholar:
#  style: _publications/ieee2.csl
#  locale: en

#  sort_by: year
#  order: descending

#  group_by: none
#  group_order: ascending

#  source: ./_publications
#  bibliography: references.bib
#  bibliography_template: {{reference}} #bibtemplate.html

#  replace_strings: true
#  join_strings:    true

  #use_raw_bibtex_entry: false

  #details_dir:    publications
  #details_layout: details.html
  #details_link:   Details

#  query: "@*"


# Gems
gems: [jekyll-paginate,rake,reduce]

#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
#  - cache/
