name: Soheil Eshghi
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Setup
title:            Soheil Eshghi
tagline:          Soheil Eshghi - Postdoctoral Associate - Yale Institute for Network Science
url:              http://www.soheileshghi.com
shorturl:         soheileshghi.com

paginate: 5
paginate_path: "/blog/page:num/"

navigation:
  - title: publications
    url: /publications/
  - title: research
    url: /research/
  - title: teaching
    url: /teaching/
  - title: professional
    url: /professional/
  - title: blog
    url: /blog/




scholar:
  style: _publications/ieee2.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_publications
  bibliography: references.bib
  bibliography_template: bibtemplate #<abbr>[{{key}}] </abbr>{{reference}} <a data-toggle="collapse" href="#{{key}}-author"> </a> ""{% if entry.author %} {% endif %}{% if entry.note %}<div class="dropdown"><button onclick="myFunction()" class="dropbtn">pre-print</button><div id="myDropdown" class="dropdown-content"><p>{{entry.note}}</p></div>    </div>{% end if %}

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  #details_dir:    publications
  #details_layout: details.html
  #details_link:   Details

  query: "@*"


# Gems
gems: [jekyll-paginate,rake,reduce]
